// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoGalaxy.Data.DbContexts;

#nullable disable

namespace RepoGalaxy.Data.Migrations
{
    [DbContext(typeof(RepoGalaxyDbContext))]
    [Migration("20260720133052_InitialV3")]
    partial class InitialV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RepoGalaxy.Data.Entities.ApiCacheEntryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StaleUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("LastAccessedAt");

                    b.HasIndex("StaleUntil");

                    b.ToTable("ApiCacheEntries");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.AuthenticationAuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuthenticationAuditEvents");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.BookmarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BookmarkedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.BookmarkTagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BookmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookmarkId", "Name")
                        .IsUnique();

                    b.ToTable("BookmarkTags");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.DiscoverySubscriptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NotificationThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("TopicsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DiscoverySubscriptions");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.FeedImpressionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("FeedImpressions");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.FeedItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CoarseScore")
                        .HasColumnType("REAL");

                    b.Property<long>("DiscoveredAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FineScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExploration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedRule")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationDelivered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsRead", "DiscoveredAt");

                    b.HasIndex("RepositoryId", "Source", "BatchId")
                        .IsUnique();

                    b.ToTable("FeedItems");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.GitIdentityAliasEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GitIdentityAliases");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.LocalContributionDayEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommitCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalRepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalRepositoryId", "Date")
                        .IsUnique();

                    b.ToTable("LocalContributionDays");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.LocalRepositoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalPath")
                        .IsUnique();

                    b.ToTable("LocalRepositories");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.NewsItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RankingBatchEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.ToTable("RankingBatches");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RankingDecisionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CoarseScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FineScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsExploration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RankingBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RankingBatchId", "RepositoryId")
                        .IsUnique();

                    b.ToTable("RankingDecisions");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.ReleaseNotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "ReleaseId")
                        .IsUnique();

                    b.ToTable("ReleaseNotifications");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CachedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("DiscoveryScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Forks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguagesJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastPushedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastViewedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenIssues")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicsJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Watchers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CachedAt");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryLanguageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Language")
                        .IsUnique();

                    b.ToTable("RepositoryLanguages");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryMetricSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("RepositoryMetricSnapshots");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryTopicEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Topic")
                        .IsUnique();

                    b.ToTable("RepositoryTopics");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.SyncCheckpointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextPageUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResumeAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "JobType", "ScopeKey")
                        .IsUnique();

                    b.ToTable("SyncCheckpoints");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.SyncRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Followers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicRepos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.UserPreferenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoCleanCache")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachePreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetailCacheTtlMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedCacheTtlMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedPageSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoredTopicsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeTrending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterestedLanguagesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterestedTopicsJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCacheSizeGB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStarsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryCacheSizeMB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStarsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewsCacheTtlMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NotificationThreshold")
                        .HasColumnType("REAL");

                    b.Property<int>("PersistentCacheSizeMB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferFreshContent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferSmallProjects")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UseSystemTheme")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.UserRepositoryRelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RelatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("AccountId", "RepositoryId", "Relation")
                        .IsUnique();

                    b.ToTable("UserRepositoryRelations");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.ViewHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferrerTopic")
                        .HasColumnType("TEXT");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ViewedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ViewHistories");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.BookmarkEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany("Bookmarks")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.BookmarkTagEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.BookmarkEntity", "Bookmark")
                        .WithMany("Tags")
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookmark");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.FeedImpressionEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.FeedItemEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany("FeedItems")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.LocalContributionDayEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.LocalRepositoryEntity", null)
                        .WithMany()
                        .HasForeignKey("LocalRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RankingDecisionEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RankingBatchEntity", null)
                        .WithMany()
                        .HasForeignKey("RankingBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryLanguageEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryMetricSnapshotEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryTopicEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.UserRepositoryRelationEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.ViewHistoryEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany("ViewHistories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.BookmarkEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryEntity", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("FeedItems");

                    b.Navigation("ViewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
