// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoGalaxy.Data.DbContexts;

#nullable disable

namespace RepoGalaxy.Data.Migrations
{
    [DbContext(typeof(RepoGalaxyDbContext))]
    [Migration("20260313164853_AddUserPreferences")]
    partial class AddUserPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("RepoGalaxy.Data.Entities.BookmarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("BookmarkedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.LocalRepositoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalPath")
                        .IsUnique();

                    b.ToTable("LocalRepositories");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("DiscoveryScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Forks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBookmarked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguagesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastPushedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastViewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenIssues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrbitCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Watchers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CachedAt");

                    b.HasIndex("IsBookmarked");

                    b.HasIndex("Stars");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Followers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicRepos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.UserPreferenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActivityScoreWeight")
                        .HasColumnType("REAL");

                    b.Property<bool>("AutoCleanCache")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DiscoveryScoreWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("FeedPageSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoredTopicsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeTrending")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InterestMatchWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("InterestedLanguagesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterestedTopicsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCacheSizeGB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStarsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStarsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferFreshContent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferSmallProjects")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PreferenceWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("QualityScoreWeight")
                        .HasColumnType("REAL");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.ViewHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferrerTopic")
                        .HasColumnType("TEXT");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ViewedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("ViewedAt");

                    b.ToTable("ViewHistories");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.BookmarkEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany("Bookmarks")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.ViewHistoryEntity", b =>
                {
                    b.HasOne("RepoGalaxy.Data.Entities.RepositoryEntity", "Repository")
                        .WithMany("ViewHistories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoGalaxy.Data.Entities.RepositoryEntity", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("ViewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
